CREATE TABLE IF NOT EXISTS Curso(
	ID INTEGER  NOT NULL AUTO_INCREMENT ,
	Nombre VARCHAR(30)  NOT NULL,
	CONSTRAINT PK_Curso PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS Assignatura(
	ID INTEGER  NOT NULL AUTO_INCREMENT ,
	Nombre VARCHAR(30)  NOT NULL,
	ID_Curso INTEGER NOT NULL,
	CONSTRAINT PK_Assignatura PRIMARY KEY(ID),
	CONSTRAINT FK_Curso_Assignatura FOREIGN KEY (ID_Curso) REFERENCES Curso(ID)
);

CREATE TABLE IF NOT EXISTS Alumno(
	ID INTEGER  NOT NULL AUTO_INCREMENT ,
	Nombre VARCHAR(30)  NOT NULL,
	Apellido VARCHAR(30) NOT NULL,
	DNI VARCHAR(9) NOT NULL,
	CONSTRAINT PK_Assignatura PRIMARY KEY(ID),
	CONSTRAINT UQ_Alumno UNIQUE(DNI)
);

CREATE TABLE IF NOT EXISTS Nota(
	ID_Assignatura INTEGER  NOT NULL,
	ID_Alumno INTEGER NOT NULL,
	Nota INT,
	CONSTRAINT PK_Nota PRIMARY KEY(ID_Assignatura,ID_Alumno),
	CONSTRAINT FK_Nota_Curso FOREIGN KEY (ID_Assignatura) REFERENCES Curso(ID),
	CONSTRAINT FK_Nota_Alumno FOREIGN KEY (ID_Alumno) REFERENCES Alumno(ID)
);
